### ISSUE TITLE
Hyku rake demo aborts due to failure to create Solr collection

### ISSUE THREAD

**Issue by seth-shaw-unlv** [samvera-deprecated/samvera-vagrant#22]
Just tried to run the hyku demo again. The rake aborted due to the hydra-development_shard1_replica_n1 SolrCore CREATE failed. See the message below:

> rake aborted!
> Failed to execute solr create: 
> Connecting to ZooKeeper at localhost:9983 ...
> INFO  - 2017-09-21 17:22:07.872; org.apache.solr.client.solrj.impl.ZkClientClusterStateProvider; Cluster at localhost:9983 ready
> Uploading /home/ubuntu/hyku-demo/solr/config for config hydra-development to ZooKeeper at localhost:9983
> 
> Creating new collection 'hydra-development' using command:
http://localhost:8983/solr/admin/collections?action=CREATE&name=hydra-development&numShards=1&replicationFactor=1&maxShardsPerNode=-1&collection.configName=hydra-development

> ERROR: Failed to create collection 'hydra-development' due to: {10.0.2.15:8983_solr=org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException:Error from server at http://10.0.2.15:8983/solr: Error CREATEing SolrCore 'hydra-development_shard1_replica_n1': Unable to create core [hydra-development_shard1_replica_n1] Caused by: Setting default operator in schema (solrQueryParser/@defaultOperator) not supported}

> . Further information may be available in /tmp/solr-7.0.0/logs
> /var/lib/gems/2.3.0/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.rb:322:in `exec'
> /var/lib/gems/2.3.0/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.rb:159:in `create'
> /var/lib/gems/2.3.0/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.rb:216:in `with_collection'
> /var/lib/gems/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/rake_support.rb:26:in `block in with_server'
> /var/lib/gems/2.3.0/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.rb:65:in `wrap'
> /var/lib/gems/2.3.0/gems/solr_wrapper-1.1.0/lib/solr_wrapper.rb:43:in `wrap'
> /var/lib/gems/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/rake_support.rb:17:in `with_server'
> /home/ubuntu/hyku-demo/Rakefile:22:in `block in <top (required)>'
> /var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
> Tasks: TOP => demo
> (See full trace by running task with --trace)

**Comment by mjgiarlo** [comment]
Hi, @seth-shaw-unlv! We're seeing this across a number of our builds. It's caused by the (unexpected) release of Solr 7, which our configs do not support. In the meantime, it should be possible to tell solr_wrapper to use Solr 6.6.1 by adding `version: 6.6.1` to the `.solr_wrapper` file.

**Comment by seth-shaw-unlv** [comment]
Attached is the solr log.
[solr.log.txt](https://github.com/samvera-labs/samvera-vagrant/files/1322220/solr.log.txt)

**Comment by seth-shaw-unlv** [comment]
I will try it. Thanks.

**Comment by seth-shaw-unlv** [comment]
That did it.

**Comment by mjgiarlo** [comment]
Great! Thanks, @seth-shaw-unlv. We can keep this issue around until we fix the root problem (supporting Solr 7).

**Comment by tdonohue** [comment]
@mjgiarlo : Just stumbled on this... pretty sure this is solved & can be closed. Hyku now supports Solr 7 per commits in this PR by you: https://github.com/samvera-labs/hyku/pull/1440

**Comment by mjgiarlo** [comment]
THanks, @tdonohue!
