### ISSUE TITLE
Blacklight Exception Thrown when clicking the "Collections" link

### ISSUE THREAD

**Issue by seth-shaw-unlv** [samvera-deprecated/samvera-vagrant#23]
Got the Hyku demo running by telling solr_wrapper to use version 6.6  (#22) , but now there is a new problem.

Attempting to view all collections (none have been created yet) generates a Blacklight Exception:

`Blacklight::Exceptions::InvalidRequest in Hyrax::My::CollectionsController#index
RSolr::Error::Http - 404 Not Found Error: Not Found URI: http://127.0.0.1:8983/solr/1661093c-9deb-49c8-bb38-7da00b7b4769/select?wt=json&qt=search&facet.field=suppressed_bsi&facet.field=admin_set_sim&facet.field=resource_type_sim&&&fq=%28%7B%21terms+f%3Dedit_access_group_ssim%7Dpublic%2Cregistered%29+OR+edit_access_person_ssim%3Atest%40unlv.edu&fq=%7B%21terms+f%3Dhas_model_ssim%7DCollection&fq=-suppressed_bsi%3Atrue&&rows=100&qf=title_tesim+description_tesim+creator_tesim+keyword_tesim&facet=true&f.admin_set_sim.facet.limit=6&f.resource_type_sim.facet.limit=6&sort=title_si+asc Backtrace: /var/lib/gems/2.3.0/gems/rsolr-2.0.2/lib/rsolr/client.rb:195:in `rescue in execute' /var/lib/gems/2.3.0/gems/rsolr-2.0.2/lib/rsolr/client.rb:185:in `execute' /var/lib/gems/2.3.0/gems/rsolr-2.0.2/lib/rsolr/client.rb:180:in `send_and_receive' /var/lib/gems/2.3.0/gems/blacklight-6.10.1/lib/blacklight/solr/repository.rb:38:in `block in send_and_receive' /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/benchmarkable.rb:41:in `block in benchmark' /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/core_ext/benchmark.rb:12:in `block in ms' /usr/lib/ruby/2.3.0/benchmark.rb:308:in `realtime' /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/core_ext/benchmark.rb:12:in `ms' /var/lib/gems/2.3.0/gems/activesupport-5.1.3/lib/active_support/benchmarkable.rb:41:in `benchmark' /var/lib/gems/2.3.0/gems/blacklight-6.10.1/lib/blacklight/solr/repository.rb:36:in `send_and_receive' /var/lib/gems/2.3.0/gems/blacklight-6.10.1/lib/blacklight/solr/repository.rb:22:in `search'`

This appears to be caused by Blacklight not finding the solr collection. Could this be related to the solr_wrapper fix noted in #22? Or is it simply because no collections have been created yet?

**Comment by jcoyne** [comment]
Looks like the solr collection hasn’t been made. Perhaps the background jobs aren’t running?

**Comment by seth-shaw-unlv** [comment]
Possibly? How would I check for the background jobs? Although, if I create a tenant, shouldn't that also create the solr collection for that tenant then? Why wait for a background job?

I just looked in the solr admin and I only see a hydra-development collection. So, _perhaps_ the real error is that creating a tenant isn't also creating the solr collection. 

Any advice on trouble-shooting this some more? Thanks.

**Comment by seth-shaw-unlv** [comment]
Creating the solr collection manually resolved this problem. So, it appears the root problem is that creating the tenant _didn't_ create a solr collection. 

However, creating a new tenant just now _did_ create the solr collection just fine. So, at this point it is an un-reproduceable bug that should probably be closed.
