### ISSUE TITLE
ffi build failure when creating new vagrant

### ISSUE THREAD

**Issue by straccers** [samvera-deprecated/samvera-vagrant#24]
I experienced persistant build fails when running  samvera-vagrant - calling bundle exec rake demo from within the hyrax demo app returned "The git source https://github.com/samvera/hyrax.git is not yet checked out. Please run `bundle install` before trying to start your application". Bundle install subsequently failed due to ffi failing to install properly. I finally got this up and running by adding the line "apt-get install libffi-dev" to the end of bootstrap.sh before running vagrant up

**Comment by escowles** [comment]
@straccers Upstream fixes have resolved this for me.  Can you confirm whether samvera-vagrant and the hyrax demo app work for you?

**Comment by escowles** [comment]
I just merged two PRs that I believe resolved this, so I'm going to close this issue.  But if you're still having problems, feel free to reopen.
