### ISSUE TITLE
Rails Version Compatibility with Hyrax Causes Vagrant Build to Fail

### ISSUE THREAD

**Issue by sgurnick** [samvera-deprecated/samvera-vagrant#27]
**Summary:**
Executing `vagrant up ` results in a system where Hyrax is not installed.

**Expected Behavior:**
At the completion of `vagrant up` I can log-in to the VM with Hyrax installed and run `bundle exec rake demo` to start all necessary processes.

**Actual Behavior:**
During the execution of `vagrant up`, the following bundler error appears:
``` Bundler could not find compatible versions for gem "actionpack":
    default:   In snapshot (Gemfile.lock):
    default:     actionpack (= 5.2.0)
    default: 
    default:   In Gemfile:
    default:     rails (~> 5.2.0) was resolved to 5.2.0, which depends on
    default:       actionpack (= 5.2.0)
    default: 
    default:     hyrax was resolved to 2.1.0.rc1, which depends on
    default:       simple_form (<= 3.5.0, ~> 3.2) was resolved to 3.2.0, which depends on
    default:         actionpack (~> 4.0)
```
This is preventing Hyrax from being installed on the vagrant VM.

**Steps to Reproduce:**
1. `git clone https://github.com/samvera-labs/samvera-vagrant.git`
2. `cd samvera-vagrant`
3. `vagrant up`
4. Watch the terminal as the VM is being set-up
5. Observe the bundler error message appear
6. `vagrant ssh`
7. `cd hyrax-demo`
8. `bundle exec rake demo`
9. Observe the following error message:
```
The git source https://github.com/samvera/hyrax.git is not yet checked out. Please run `bundle install` before trying to start your application
```
10. Run `bundle install` as it suggests
11. Receive the same error message as before with respect to versioning issues

**Troubleshooting and Workaround:**
I walked through the[ install scripts](https://github.com/samvera-labs/samvera-vagrant/tree/master/install_scripts) manually on a new VM to see if I could pin-point where the problem starts. 

It appears that the default is to install the latest version of Rails, which as of 2018-05-15 is 5.2.0. However, the version of Hyrax being installed is 2.1.0rc2, which seems to depend on Rails 5.1.X or earlier. To resolve this, I installed the latest 5.1 minor version of Rails manually, which as of 2018-05-15 is 5.1.6. 

Steps:

1. Uninstall Rails 5.2.0:
```
$ sudo gem uninstall concurrent-ruby i18n thread_safe tzinfo activesupport rack rack-test mini_portile2 nokogiri crass loofah rails-html-sanitizer rails-dom-testing builder erubi actionview actionpack activemodel arel activerecord globalid activejob mini_mime mail actionmailer nio4r websocket-extensions websocket-driver actioncable mimemagic marcel activestorage thor method_source railties sprockets sprockets-rails rails
```
2. Install Rails 5.1.6:
```
$ sudo gem install rails -v 5.1.6 --no-ri --no-rdoc
```
3. Remove the hyrax-demo directory
```
rm -rf hyrax-demo
```
4. Begin running the steps outlined in the [demo-app.sh](https://github.com/samvera-labs/samvera-vagrant/blob/master/install_scripts/demo-app.sh) script
5. The `bundle install` and all subsequent steps execute successfully - resulting in a working Hyrax installation.

**Comment by nicholsn** [comment]
@sgurnick thanks for this. I observed the same error and the steps you outlined here got me to a working installation.

I'll note that I also observed the following error that I needed to correct before bringing the system online:

```
bundle exec rake demo
rake aborted!
Failed to execute solr start: *** [WARN] *** Your open file limit is currently 1024.
 It should be set to 65000 to avoid operational disruption.
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
```

**Comment by straccers** [comment]
Hi. we cloned the lock-rails5.1-fix-bundle branch but found we also needed to make a couple of further edits before we could build and start the demo successfully 1) add the line apt-get install libcurl3  to end of bootstrap.sh 2) change sudo -u postgres createuser ubuntu --superuser to sudo -u postgres createuser vagrant  --superuser in postgres.sh

**Comment by sgurnick** [comment]
@straccers - I observed the same behavior with regard to the postgres database user creation. I submitted #28 around the same time as this issue (#27) to document this behavior and hopefully get it addressed as well.

**Comment by DOTang** [comment]
I had a similar issue, I followed the above and got errored out at this line:

> bundle exec rails generate hyrax:install -f -q

With the error:

> Rails Error: Unable to access log file. Please ensure that /hyrax-demo/log/development.log exists and is writable (ie, make it writable for user and group: chmod 0664 /hyrax-demo/log/development.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
Could not find generator 'hyrax:install'. Maybe you meant 'channel', 'assets' or 'mailer'

Not sure what to do now.

**Comment by escowles** [comment]
@DOTang I merged the outstanding PRs and spun up the vagrant locally, and was able to build and run Hyrax and Hyku without problems.  Can you re-try?

**Comment by DOTang** [comment]
Yep, works now, thanks.
