### ISSUE TITLE
Could not find gem 'sufia (= 7.0.0.beta4)'

### ISSUE THREAD

**Issue by yinlinchen** [samvera-deprecated/samvera-vagrant#6]
1. git clone https://github.com/projecthydra-labs/hydra-vagrant.git
2. cd hydra-vagrant
3. vagrant up

== Error message==
==> default: /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:356:in `block in verify_gemfile_dependencies_are_found!'
==> default: : 
==> default: Could not find gem 'sufia (= 7.0.0.beta4)' in any of the gem sources listed in your Gemfile or available on this machine.
==> default:  (
==> default: Bundler::GemNotFound
==> default: )
==> default:    from /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:331:in`each'
==> default:    from /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:331:in `verify_gemfile_dependencies_are_found!'
==> default:    from /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:200:in`start'
==> default:    from /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:184:in `resolve'
==> default:    from /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in`resolve'
==> default:    from /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
==> default:    from /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:185:in`specs_for'
==> default:    from /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:174:in `requested_specs'
==> default:    from /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/environment.rb:19:in`requested_specs'
==> default:    from /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:14:in `setup'
==> default:    from /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler.rb:95:in`setup'
==> default:    from /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/setup.rb:19:in `<top (required)>'
==> default:    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in`require'
==> default:    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
==> default:    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in`require'
==> default:    from /home/vagrant/sufia-demo/config/boot.rb:3:in `<top (required)>'
==> default:    from bin/rails:3:in`require_relative'
==> default:    from bin/rails:3:in `<main>'
==> default: rake aborted!
==> default: Bundler::GemNotFound: Could not find gem 'sufia (= 7.0.0.beta4)' in any of the gem sources listed in your Gemfile or available on this machine.

**Comment by jcoyne** [comment]
Fixed by https://github.com/projecthydra-labs/hydra-vagrant/pull/7
